# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x        
    - name: Build
      run: |
        cd Program
        dotnet restore
        dotnet build --no-restore
    - name: Test
      run: |
        cd Tests
        dotnet restore
        dotnet build --no-restore
        dotnet run --project Tests.csproj
        if [ $? -ne 0 ]; then
          echo "Test failed!"
          exit 1
        fi
